Update probe_bash.go
gojue/ecapture pull request #479
Opened 2024-02-05 04:11 UTC by sancppp

Fixed a text error in a comment

2024-02-05 06:37 UTC, cfc4n requested changes
感谢贡献。这个pr只是修改了注释，能否也参与做一些代码上的贡献呢？比如，bash模块有个缺陷，在启动ecapture后，第一个bash命令监控不到，丢失了。能否定位一下这个bug，一起修复了？非常感谢。

------

Thank you for your contribution. This PR only modified the comments. Can you also contribute to some code changes? For example, there is a defect in the bash module where the first bash command cannot be monitored and is lost after starting ecapture. Could you help locate this bug and fix it together? Thank you very much.

2024-02-05 11:07 UTC, sancppp commented
> 感谢贡献。这个pr只是修改了注释，能否也参与做一些代码上的贡献呢？比如，bash模块有个缺陷，在启动ecapture后，第一个bash命令监控不到，丢失了。能否定位一下这个bug，一起修复了？非常感谢。
> 
> Thank you for your contribution. This PR only modified the comments. Can you also contribute to some code changes? For example, there is a defect in the bash module where the first bash command cannot be monitored and is lost after starting ecapture. Could you help locate this bug and fix it together? Thank you very much.

首先，我去测试了一下BCC中的bashreadline工具，发现也有同样的问题。

再用uprobe/uretprobe给bash::readline这个函数打断点，发现bash的运行会阻塞在readline这个函数，当接收到回车时获取缓冲区内容。表现为新建一个bash terminal时会触发uprobe，输入回车之后会触发uretprobe打印出输入的命令然后立刻触发uprobe。因此使用uretprobe去监控bash::readline会丢失第一个命令。

然后我下载了gnu bash 5.1.16的源码，得知了readline函数的返回值是由readline_internal_teardown这个函数得来的。
**将hook函数由readline更改为readline_internal_teardown之后，能够解决eCapture bash启动后第一个命令丢失的问题。**

另外，我翻阅了老版本的bash，1996年的bash2.0版本中也是相同的函数处理流程，因此应该不需要判断bash的版本来判断hook哪个函数。

如果您觉得这个更改没问题的话，晚些时候我也去给BCC提个PR。

2024-02-05 12:15 UTC, cfc4n commented on user/module/probe_bash.go
> +				AttachToFuncName: "readline_internal_teardown",
为什么换成readline_internal_teardown这个函数呢？ 能否补充一些说明？

2024-02-05 12:17 UTC, cfc4n commented
感谢分析，对于定位的原因，能否贴一些bash对应hook函数的代码片段？

2024-02-05 15:37 UTC, sancppp commented
[bash::readline.c代码片段：](https://github.com/bminor/bash/blob/master/lib/readline/readline.c#L734)
```c
#if defined (READLINE_CALLBACKS)
#  define STATIC_CALLBACK
#else
#  define STATIC_CALLBACK static
#endif


STATIC_CALLBACK char *
readline_internal_teardown (int eof)
{
  ...
  return (eof ? (char *)NULL : savestring (the_line));
}


/* Read a line of input from the global rl_instream, doing output on
   the global rl_outstream.
   If rl_prompt is non-null, then that is our prompt. */
static char *
readline_internal (void)
{
  readline_internal_setup ();
  rl_eof_found = readline_internal_charloop ();
  return (readline_internal_teardown (rl_eof_found));
}


/* Read a line of input.  Prompt with PROMPT.  An empty PROMPT means
   none.  A return value of NULL means that EOF was encountered. */
char *
readline (const char *prompt)
{
  char *value;
  ...
  value = readline_internal (); //阻塞等待，直到收到回车键信号
  ...
  return (value);
}
```

可见：
1. `readline`函数通过调用`static`修饰的函数`readline_internal`阻塞等待用户输入的命令。
2. `readline_internal`在接受回车键信号后调用`STATIC_CALLBACK`宏修饰的`readline_internal_teardown`函数进行返回。
3. `STATIC_CALLBACK`受`READLINE_CALLBACKS`约束。

而[bash::rlconf.h](https://github.com/bminor/bash/blob/master/lib/readline/rlconf.h#L60)中默认开启了`READLINE_CALLBACKS`。

因此：
1. 在bash的符号表中没有`static`修饰的函数`readline_internal`，无法作为ebpf的hook函数。
2. 若要解决eCapture bash启动后第一次bash命令丢失的问题，需要将hook函数由`readline`更改为`readline_internal_teardown`。

2024-02-06 15:35 UTC, cfc4n approved these changes
LGTM，thanks.

2024-02-07 23:15 UTC, sancppp commented
https://github.com/iovisor/bcc/pull/4903 给BCC交的补丁被merge了。

2024-02-08 04:59 UTC, cfc4n commented
> https://github.com/iovisor/bcc/pull/4903 给BCC交的补丁被merge了，感谢大佬给的机会😍。

恭喜，希望这可以引领你走上一个新台阶。

2024-02-08 05:00 UTC, merged